name: native_json_api
description: native_json_api package project
version: 2026.111.1154
homepage: 
repository: https://github.com/dart-pkg/native_json_api

environment:
  sdk: ^3.7.2
dependencies:
  dynamic_function: ^2025.427.1341
  ffi: ^2.1.5
dev_dependencies:
  lints: ^6.0.0
  output: ^2025.502.1958
  test: ^1.29.0
